version: '3'
services:
  # -----------------------------------------------------------------------------------
  zookeeper:
    image: bitnami/zookeeper:3.6.0
    ports:
      - 2181:2181
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  # -----------------------------------------------------------------------------------
  kafka:
    image: bitnami/kafka:2.5.0
    ports:
      - 9092:9092
      - 29092:29092
    depends_on:
      - zookeeper
    environment:
      - KAFKA_HEAP_OPTS=-Xmx192m -Xms192m
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=INTERNAL://:9092,EXTERNAL://:29092
      - KAFKA_CFG_ADVERTISED_LISTENERS=INTERNAL://kafka:9092,EXTERNAL://${DOCKER_HOST_IP:-localhost}:29092
      - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL
  # -----------------------------------------------------------------------------------
  openapi-product-service:
    image: registry.cn-shenzhen.aliyuncs.com/isfong/cors-swagger-ui:v3.39.0
    ports:
      - 80:8080
    volumes:
      - ../cnm-inventory-product-sdk/src/main/resources:/resources
    environment:
      SWAGGER_JSON: /resources/openapi.yaml
      # Automatically intercepts each path proxy to the URI before the path
      CORS: http://192.168.101.207:8080/products,http://192.168.101.207:8080/inventories,http://192.168.101.207:8080/orders
  # -----------------------------------------------------------------------------------
  postgres-product-service:
    image: registry.cn-shenzhen.aliyuncs.com/isfong/eventuate-tram-sagas-postgres:13.1
    ports:
      - 5431:5432
    environment:
      POSTGRES_DB: cnm-product-service
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
  # -----------------------------------------------------------------------------------
  postgres-inventory-service:
    image: registry.cn-shenzhen.aliyuncs.com/isfong/eventuate-tram-sagas-postgres:13.1
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: cnm-inventory-service
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
  # -----------------------------------------------------------------------------------
  postgres-order-service:
    image: registry.cn-shenzhen.aliyuncs.com/isfong/eventuate-tram-sagas-postgres:13.1
    ports:
      - 5433:5432
    environment:
      POSTGRES_DB: cnm-order-service
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
  # -----------------------------------------------------------------------------------
  cdc-service:
    image: eventuateio/eventuate-cdc-service:0.9.0.RELEASE
    ports:
      - "9090:8080"
    depends_on:
      - zookeeper
      - kafka
      - postgres-product-service
    environment:
      SPRING_PROFILES_ACTIVE: PostgresWal
      LOGGING_LEVEL_IO_EVENTUATE: INFO
      EVENTUATELOCAL_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      EVENTUATELOCAL_ZOOKEEPER_CONNECTION_STRING: zookeeper:2181

      EVENTUATE_CDC_PIPELINE_PIPELINEPRODUCTSERVICE_TYPE: eventuate-tram
      EVENTUATE_CDC_PIPELINE_PIPELINEPRODUCTSERVICE_READER: ProductService
      EVENTUATE_CDC_PIPELINE_PIPELINEPRODUCTSERVICE_EVENTUATEDATABASESCHEMA: eventuate
      EVENTUATE_CDC_READER_PRODUCTSERVICE_TYPE: postgres-wal
      EVENTUATE_CDC_READER_PRODUCTSERVICE_DATASOURCEURL: jdbc:postgresql://postgres-product-service/cnm-product-service
      EVENTUATE_CDC_READER_PRODUCTSERVICE_DATASOURCEUSERNAME: postgres
      EVENTUATE_CDC_READER_PRODUCTSERVICE_DATASOURCEPASSWORD: postgres
      EVENTUATE_CDC_READER_PRODUCTSERVICE_DATASOURCEDRIVERCLASSNAME: org.postgresql.Driver
      EVENTUATE_CDC_READER_PRODUCTSERVICE_LEADERSHIPLOCKPATH: /eventuatelocal/cdc/leader/pipeline/cnm-product-service

      EVENTUATE_CDC_PIPELINE_PIPELINEINVENTORYSERVICE_TYPE: eventuate-tram
      EVENTUATE_CDC_PIPELINE_PIPELINEINVENTORYSERVICE_READER: InventoryService
      EVENTUATE_CDC_PIPELINE_PIPELINEINVENTORYSERVICE_EVENTUATEDATABASESCHEMA: eventuate
      EVENTUATE_CDC_READER_INVENTORYSERVICE_TYPE: postgres-wal
      EVENTUATE_CDC_READER_INVENTORYSERVICE_DATASOURCEURL: jdbc:postgresql://postgres-inventory-service/cnm-inventory-service
      EVENTUATE_CDC_READER_INVENTORYSERVICE_DATASOURCEUSERNAME: postgres
      EVENTUATE_CDC_READER_INVENTORYSERVICE_DATASOURCEPASSWORD: postgres
      EVENTUATE_CDC_READER_INVENTORYSERVICE_DATASOURCEDRIVERCLASSNAME: org.postgresql.Driver
      EVENTUATE_CDC_READER_INVENTORYSERVICE_LEADERSHIPLOCKPATH: /eventuatelocal/cdc/leader/pipeline/cnm-inventory-service

      EVENTUATE_CDC_PIPELINE_PIPELINEORDERSERVICE_TYPE: eventuate-tram
      EVENTUATE_CDC_PIPELINE_PIPELINEORDERSERVICE_READER: OrderService
      EVENTUATE_CDC_PIPELINE_PIPELINEORDERSERVICE_EVENTUATEDATABASESCHEMA: eventuate
      EVENTUATE_CDC_READER_ORDERSERVICE_TYPE: postgres-wal
      EVENTUATE_CDC_READER_ORDERSERVICE_DATASOURCEURL: jdbc:postgresql://postgres-order-service/cnm-order-service
      EVENTUATE_CDC_READER_ORDERSERVICE_DATASOURCEUSERNAME: postgres
      EVENTUATE_CDC_READER_ORDERSERVICE_DATASOURCEPASSWORD: postgres
      EVENTUATE_CDC_READER_ORDERSERVICE_DATASOURCEDRIVERCLASSNAME: org.postgresql.Driver
      EVENTUATE_CDC_READER_ORDERSERVICE_LEADERSHIPLOCKPATH: /eventuatelocal/cdc/leader/pipeline/cnm-order-service
  # -----------------------------------------------------------------------------------