releases:
  - name: cnm-product-service
    namespace: cnm
    chart: charts/cnm-product-service
    values:
      - image:
          tag: {{ env "CNM_PRODUCT_SERVICE_VERSION" | default "" }}

  - name: cnm-inventory-service
    namespace: cnm
    chart: charts/cnm-inventory-service
    values:
      - image:
          tag: {{ env "CNM_INVENTORY_SERVICE_VERSION" | default "" }}

  - name: cnm-order-service
    namespace: cnm
    chart: charts/cnm-order-service
    values:
      - image:
          tag: {{ env "CNM_ORDER_SERVICE_VERSION" | default "" }}