repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
releases:
  - name: kafka
    namespace: example
    chart: bitnami/kafka
    version: 12.5.0
    wait: true

  - name: example-product-service
    namespace: example
    chart: charts/example-product-service
    values:
      - image:
          tag: {{ env "EXAMPLE_PRODUCT_SERVICE_VERSION" | default "" }}
  - name: postgres-product-service
    namespace: example
    chart: bitnami/postgresql
    version: 10.2.1
    wait: false
    values:
      - image:
          repository: registry.cn-shenzhen.aliyuncs.com/isfong/eventuate-tram-sagas-postgres
          tag: 13.1
      - postgresqlDatabase: example-product-service
      - postgresqlUsername: postgres
      - postgresqlPassword: postgres

  - name: example-inventory-service
    namespace: example
    chart: charts/example-inventory-service
    values:
      - image:
          tag: {{ env "EXAMPLE_INVENTORY_SERVICE_VERSION" | default "" }}
  - name: postgres-inventory-service
    namespace: example
    chart: bitnami/postgresql
    version: 10.2.1
    wait: false
    values:
      - image:
          repository: registry.cn-shenzhen.aliyuncs.com/isfong/eventuate-tram-sagas-postgres
          tag: 13.1
      - postgresqlDatabase: example-inventory-service
      - postgresqlUsername: postgres
      - postgresqlPassword: postgres

  - name: example-order-service
    namespace: example
    chart: charts/example-order-service
    values:
      - image:
          tag: {{ env "EXAMPLE_ORDER_SERVICE_VERSION" | default "" }}
  - name: postgres-order-service
    namespace: example
    chart: bitnami/postgresql
    version: 10.2.1
    wait: false
    values:
      - image:
          repository: registry.cn-shenzhen.aliyuncs.com/isfong/eventuate-tram-sagas-postgres
          tag: 13.1
      - postgresqlDatabase: example-order-service
      - postgresqlUsername: postgres
      - postgresqlPassword: postgres