repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
releases:
  - name: postgres-product-service
    namespace: cnm
    chart: bitnami/postgresql
    version: 10.2.1
    wait: false
    values:
      - image:
          repository: registry.cn-shenzhen.aliyuncs.com/isfong/eventuate-tram-sagas-postgres
          tag: 13.1
      - postgresqlDatabase: cnm-product-service
      - postgresqlUsername: postgres
      - existingSecret: secret-postgres-product-service-password
      - persistence:
#          existingClaim: data-postgres-product-service-postgresql-0
          storageClass: nfs-client

  - name: postgres-inventory-service
    namespace: cnm
    chart: bitnami/postgresql
    version: 10.2.1
    wait: false
    values:
      - image:
          repository: registry.cn-shenzhen.aliyuncs.com/isfong/eventuate-tram-sagas-postgres
          tag: 13.1
      - postgresqlDatabase: cnm-inventory-service
      - postgresqlUsername: postgres
      - existingSecret: secret-postgres-inventory-service-password
      - persistence:
#          existingClaim: data-postgres-inventory-service-postgresql-0
          storageClass: nfs-client

  - name: postgres-order-service
    namespace: cnm
    chart: bitnami/postgresql
    version: 10.2.1
    wait: false
    values:
      - image:
          repository: registry.cn-shenzhen.aliyuncs.com/isfong/eventuate-tram-sagas-postgres
          tag: 13.1
      - postgresqlDatabase: cnm-order-service
      - postgresqlUsername: postgres
      - existingSecret: secret-postgres-order-service-password
      - persistence:
#          existingClaim: data-postgres-order-service-postgresql-0
          storageClass: nfs-client