title: ProductRepresentation
type: object
description: Product details
properties:
  id:
    type: string
    description: Product ID
  name:
    type: string
    description: The product name
  description:
    type: string
    description: The Product Description
  price:
    type: number
    format: double
    description: The Product Price
  createdAt:
    type: integer
    format: int64
    description: Created time
  inventory:
    type: integer
    description: Inventory levels
  categoryId:
    type: string
    description: Category ID
required:
  - id
  - name
  - description
  - price
  - createdAt
  - inventory
  - categoryId
x-tags:
  - product
