repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
releases:
  - name: kafka
    namespace: cnm
    chart: bitnami/kafka
    version: 12.5.0
    wait: true
    values:
      - persistence:
#          existingClaim: data-kafka-0
          storageClass: nfs-client
      - zookeeper:
          persistence:
#            existingClaim: data-kafka-zookeeper-0
            storageClass: nfs-client