apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: cnm-k8s-bossdream-com-gw
  namespace: cnm
spec:
  selector:
    app: istio-ingressgateway
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - k8s.bossdream.com
      tls:
        httpsRedirect: true # sends 301 redirect for http requests
    - port:
        number: 443
        name: https
        protocol: HTTPS
      hosts:
        - k8s.bossdream.com
      tls:
        mode: SIMPLE
        credentialName: tls.k8s.bossdream.com
