apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: cnm-isfong-com-vs
  namespace: cnm
spec:
  hosts:
    - k8s.bossdream.com
  gateways:
    - cnm-k8s-bossdream-com-gw
  http:
    - match:
        - uri:
            prefix: /products
      route:
        - destination:
            host: cnm-api-gateway-service.cnm.svc.cluster.local
    - match:
        - uri:
            prefix: /categories
      route:
        - destination:
            host: cnm-api-gateway-service.cnm.svc.cluster.local
    - match:
        - uri:
            prefix: /inventories
      route:
        - destination:
            host: cnm-api-gateway-service.cnm.svc.cluster.local
    - match:
        - uri:
            prefix: /orders
      route:
        - destination:
            host: cnm-api-gateway-service.cnm.svc.cluster.local
## default
#    - route:
#        - destination:
#            host: ng-bossdream.bossdream.svc.cluster.local
