spring:
  output:
    ansi:
      enabled: always
  cloud:
    gateway:
      routes:
        - id: product-service
          uri: http://cnm-product-service.cnm.svc.cluster.local
          predicates:
            - Path=/products/**,/categories/**
          filters:
            - StripPrefix=0 # This configuration can be ignored. Just note that you can modify the access path.
        - id: inventory-service
          uri: http://cnm-inventory-service.cnm.svc.cluster.local
          predicates:
            - Path=/inventories/**
        - id: order-service
          uri: http://cnm-order-service.cnm.svc.cluster.local
          predicates:
            - Path=/orders/**
management:
  endpoints:
    web:
      exposure:
        include: "*"
