openapi: 3.0.0
info:
  title: 库存管理API
  version: '1.0'
  description: 库存管理API
  contact:
    email: isfong@qq.com
servers:
  - url: 'http://localhost:8080'
paths:
  '/inventories/{id}':
    parameters:
      - schema:
          type: integer
          format: int64
        name: id
        in: path
        required: true
        description: 库存ID
    get:
      summary: 查询库存
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InventoryRepresentation'
      operationId: getInventory
      description: 更加库存ID查询库存
  '/inventories/{id}/increase':
    parameters:
      - schema:
          type: integer
          format: int64
        name: id
        in: path
        required: true
        description: 库存ID
    post:
      summary: 增加库存量
      operationId: increaseInventory
      responses:
        '204':
          description: 已修改
      description: 根据库存ID增加库存量
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/IncreaseInventoryCommand'
        description: 增加库存命令
      tags:
        - inventory
  '/inventories/with-product/{productId}':
    parameters:
      - schema:
          type: string
        name: productId
        in: path
        required: true
        description: 产品ID
    get:
      summary: 查询一个产品库存
      tags:
        - inventory
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InventoryRepresentation'
      operationId: getInventoryWithProduct
      description: 根据产品ID查询库存
components:
  schemas:
    IncreaseInventoryCommand:
      title: IncreaseInventoryCommand
      type: object
      description: 增加库存命令
      properties:
        numberOfIncreaseInventory:
          type: integer
          description: 增加数量
      required:
        - numberOfIncreaseInventory
      x-tags:
        - inventory
    InventoryRepresentation:
      title: InventoryRepresentation
      type: object
      description: 库存信息
      properties:
        id:
          type: integer
          format: int64
          description: 库存ID
        createdAt:
          type: integer
          description: 创建时间
          format: int64
        updatedAt:
          type: integer
          format: int64
          description: 更新时间
        version:
          type: integer
          format: int64
          description: 模型版本
        productId:
          type: string
          description: 产品ID
        productName:
          type: string
          description: 产品名称
        remains:
          description: 库存量
          type: integer
      required:
        - id
        - createdAt
        - updatedAt
        - version
        - productId
        - productName
        - remains
      x-tags:
        - inventory
tags:
  - name: inventory
