openapi: 3.0.0
info:
  title: 产品管理
  version: '1.0'
  contact:
    email: isfong@qq.com
  description: 产品管理相关API
servers:
  - url: 'http://localhost:8080'
paths:
  /products:
    get:
      summary: 产品列表查询
      tags:
        - product
      responses:
        '200':
          description: 查询OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PagedRepresentations'
      operationId: pagedProducts
      description: 查询分页产品列表
      parameters:
        - schema:
            type: integer
            default: 1
          in: query
          name: page
          description: 页码
        - schema:
            type: integer
            default: 10
          in: query
          name: size
          description: 每页数据量
    post:
      summary: 创建产品
      operationId: createProduct
      responses:
        '201':
          description: 已创建
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateProductRepresentation'
      description: 创建产品API
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateProductCommand'
        description: 创建产品发送命令
      tags:
        - product
  '/products/{id}':
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
        description: 产品ID
    get:
      summary: 查询单个产品
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductRepresentation'
        '404':
          description: Not Found
      operationId: getProduct
      description: 根据产品ID查询产品
  '/products/{id}/name':
    put:
      summary: 修改一个产品的名称
      operationId: changeProductName
      description: 根据产品ID修改产品名称
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ChangeProductNameCommand'
        description: 修改产品名称发送命令
      responses:
        '204':
          description: 已修改
      tags:
        - product
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
        description: 产品ID
  /categories:
    post:
      summary: 创建类别
      operationId: createCategory
      responses:
        '201':
          description: 已创建
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateCategoryRepresentation'
      description: 创建一个产品类别
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateCategoryCommand'
        description: 创建类别发送命令
      tags:
        - product
        - category
  '/categories/{id}':
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
        description: 类别ID
    get:
      summary: 查询一个类别
      tags:
        - product
        - category
      responses:
        '200':
          description: 已找到
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CategoryRepresentation'
        '404':
          description: 未找到
      operationId: getCategory
      description: 根据类别ID查询一个类别
components:
  schemas:
    CreateProductRepresentation:
      title: CreateProductRepresentation
      type: object
      description: 创建产品响应信息
      properties:
        id:
          type: string
          description: 产品ID
      required:
        - id
      x-tags:
        - product
    CreateProductCommand:
      title: CreateProductCommand
      type: object
      properties:
        name:
          type: string
          description: 产品名称
        description:
          type: string
          description: 产品描述
        price:
          type: number
          format: double
          description: 产品价格
        categoryId:
          type: string
          description: 产品类别ID
      required:
        - name
        - description
        - price
        - categoryId
      description: 创建产品命令
      x-tags:
        - product
    ProductRepresentation:
      title: ProductRepresentation
      type: object
      description: 产品详情
      properties:
        id:
          type: string
          description: 产品ID
        name:
          type: string
          description: 产品名称
        description:
          type: string
          description: 产品描述
        price:
          type: string
          description: 产品价格
        createdAt:
          type: integer
          format: int64
          description: 创建时间
        inventory:
          type: integer
          description: 库存
        categoryId:
          type: string
          description: 类别ID
      required:
        - id
        - name
        - description
        - price
        - createdAt
        - inventory
        - categoryId
      x-tags:
        - product
    PagedRepresentations:
      title: PagedRepresentations
      type: object
      description: 分页表示信息
      properties:
        total:
          type: integer
          description: 总记录数
        page:
          type: integer
          description: 页码
        representations:
          type: array
          description: 数据列表
          items:
            $ref: '#/components/schemas/ProductRepresentation'
      required:
        - total
        - page
        - representations
    ChangeProductNameCommand:
      title: ChangeProductNameCommand
      type: object
      properties:
        newName:
          type: string
          description: 新名称
      required:
        - newName
      description: 修改产品名称命令信息
    CreateCategoryCommand:
      title: CreateCategoryCommand
      type: object
      properties:
        name:
          type: string
          description: 名称
        description:
          type: string
          description: 描述
      required:
        - name
        - description
      description: 创建类别命令信息
    CreateCategoryRepresentation:
      title: CreateCategoryRepresentation
      type: object
      description: 创建类别响应信息
      properties:
        id:
          type: string
          description: 新类别ID
      required:
        - id
    CategoryRepresentation:
      title: CategoryRepresentation
      type: object
      description: 产品类别信息
      properties:
        id:
          type: string
          description: ID
        name:
          type: string
          description: 名称
        description:
          type: string
          description: 描述
        createdAt:
          type: integer
          description: 创建时间
          format: int64
      required:
        - id
        - name
        - description
        - createdAt
  responses: {}
tags:
  - name: product
  - name: category
